version: '3.7'

services:
  app-server:
    image: adn-hotel:latest
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    networks:
      - net
  db:
    image: mysql:5.7
    ports:
      - "33066:3306"
    restart: always
    environment:
      MYSQL_DATABASE: db_hotel
      MYSQL_USER: sophia
      MYSQL_PASSWORD: ssaa
      MYSQL_ROOT_PASSWORD: ssaa
    networks:
      - net
volumes:
  db-data:

networks:
  net: